webserver:
  port: 3000
  url: "http://localhost:3000"

hostname:
  city: "*.localhost"
  website: "localhost"

# Use virtual hosts for multiple hostnames, if true the engine will also require
# an entry in "/etc/hosts" of: 127.0.0.1  api.localhost
usevhosts: true

# Multiple Nodes running concurently.
multipleNodes: false

# Google Analytics key
ga: "UA-XXXXX-X"

logger:
  # Log Levels:
  # SEVERE: 1000
  # WARN:   800
  # INFO:   600
  # FINE:   400
  # FINER:  200
  # FINEST: 100
  level: 100
  syslog: false
  file: false
  saveToFile: false
  console: true
  filename: "./logs/app.log"

mongo:
  hostname: localhost
  database: app
  # Attempt to reconnect interval in ms.
  reconnectTime: 500

redis:
  namespace: "wetech:"
  main:
    host: "localhost"
    port: 6379
  sessionWeb:
    # https://github.com/visionmedia/connect-redis#options
    host: "localhost"
    port: 6379
    prefix: "appSessionWeb:"
  sessionCity:
    host: "localhost"
    port: 6379
    prefix: "appSessionCity:"
  kansas:
    port: 6379
    host: "localhost"
    pass: ""
  idify:
    port: 6379
    host: "localhost"
    pass: ""

cookies:
  website:
    # domain: ".localhost"
    name: 'app'
    session:
      secret: "zzz"
      maxAge: null
  city:
    # domain: ".city.localhost"
    name: 'city'
    session:
      secret: "xxx"
      maxAge: null

users:
  # Durations in milliseconds:
  # 1 day:      86400000
  # 1 week:    604800000
  # 1 month:  2592000000
  # 3 months: 7776000000
  emailConfirmationExpires: 7776000000
  passwordResetExpires: 604800000

crypto:
  salt: "zzz"

mandrill:
  apikey: "xxx"
  apikeyStub: "xxx"

test:
  hostname: "localhost"
  port: 3000
  apiPort: 3001

# This is about the API websocket server
websocket:
  # The time to wait for a challenge to complete, in milliseconds.
  challengeTimeout: 6000

  # The timeout for the client, when it closes the connection it still X amounts
  # of seconds to do re open of the connection. This value is sent to the
  # client after a successful handshake.
  closeTimeout: 60

  # The begin point where Socket.IO starts looking for incoming connections.
  # This should be the same between the client and the server.
  # WARNING: do not change this value or socket.io breaks (!)
  resource: "socket.io"

data:
  city:
    - name: "Thessaloniki"
    headerTitle: "SKGTech"
    hostname: "skg.localhost"
    domainName: "skg.localhost"
    twitter: "SKG_Tech"
    facebook: "skgtech.io"
    calendarUrl: "2ul10sd9g30mnk1vpmcnnp5qv4@group.calendar.google.com"
    calendarApiKey: "AIzaSyC75rnKyEkGxmVyG7hlqFicwPBgDmQLN_w"
    forumUrl: "https://groups.google.com/forum/#!forum/skg-developers"
    og:
      title: "Thessaloniki tech and developer Meetups"
      siteName: "SKGTech"
      url: "skg.localhost"
      description: "Thessaloniki tech and developer Meetups"
      image: "https://pbs.twimg.com/profile_images/453243331691020288/pk_2bTE9.png"
      appId: "698696243515776"
      type: "website"
    ga: "UA-41787746-3"
    redirects:
      together-apr-2014: "http://together.skgtech.io/together-apr-2014/"
    - name: "Athens"
    headerTitle: "ATHTech"
    hostname: "ath.localhost"
    domainName: "ath.localhost"
    twitter: "ATHTechGR"
    facebook: "athtech.org"
    calendarUrl: "oo1mlkql8sma2b3pkg6i23qtdc@group.calendar.google.com"
    calendarApiKey: "AIzaSyCccutOwOmeR_0gKxpOk5YUbEPLyMC8WWM"
    forumUrl: "https://groups.google.com/forum/#!forum/ath-developers"
    og:
      title: "Athens tech and developer Meetups"
      siteName: "ATHTech"
      url: "ath.localhost"
      description: "Athens tech and developer Meetups"
      image: "https://pbs.twimg.com/profile_images/460206458559139840/JAVly4k1.jpeg"
      appId: "698696243515776"
      type: "website"
    ga: "UA-50423318-1"
