webserver:
  port: 80

hostname:
  city: "*.wearetech.io"
  website: "wearetech.io"

# Google Analytics key
ga: "UA-xxxxxx-2"

logger:
  # Log Levels:
  # SEVERE: 1000
  # WARN:   800
  # INFO:   600
  # FINE:   400
  # FINER:  200
  # FINEST: 100
  level: 200
  syslog: false
  file: false
  console: true
  filename: "./logs/app.log"

data:
  city:
    - name: "Thessaloniki"
    headerTitle: "SKGTech"
    hostname: "skgtech.io"
    domainName: "skgtech.io"
    twitter: "SKG_Tech"
    facebook: "skgtech.io"
    calendarUrl: "2ul10sd9g30mnk1vpmcnnp5qv4@group.calendar.google.com"
    calendarApiKey: "AIzaSyC75rnKyEkGxmVyG7hlqFicwPBgDmQLN_w"
    forumUrl: "https://groups.google.com/forum/#!forum/skg-developers"
    og:
      title: "Thessaloniki tech and developer Meetups"
      siteName: "SKGTech"
      url: "skgtech.io"
      description: "Thessaloniki tech and developer Meetups"
      image: "https://pbs.twimg.com/profile_images/453243331691020288/pk_2bTE9.png"
      appId: "698696243515776"
      type: "website"
    ga: "UA-41787746-3"
    redirects:
      together-apr-2014: "http://together.skgtech.io/together-apr-2014/"
    - name: "Athens"
    headerTitle: "ATHTech"
    hostname: "www.athtech.org"
    domainName: "athtech.org"
    twitter: "ATHTechGR"
    facebook: "athtech.org"
    calendarUrl: "oo1mlkql8sma2b3pkg6i23qtdc@group.calendar.google.com"
    calendarApiKey: "AIzaSyCccutOwOmeR_0gKxpOk5YUbEPLyMC8WWM"
    forumUrl: "https://groups.google.com/forum/#!forum/ath-developers"
    og:
      title: "Athens tech and developer Meetups"
      siteName: "ATHTech"
      url: "athtech.org"
      description: "Athens tech and developer Meetups"
      image: "https://pbs.twimg.com/profile_images/460206458559139840/JAVly4k1.jpeg"
      appId: "698696243515776"
      type: "website"
    ga: "UA-50423318-1"
